"""empty message

Revision ID: 5665f99cadff
Revises: 50f4ad104198
Create Date: 2020-12-01 21:17:18.892220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5665f99cadff'
down_revision = '50f4ad104198'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'UsersArticles', 'User', ['moderator_ID'], ['user_ID'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'UsersArticles', type_='foreignkey')
    # ### end Alembic commands ###
